User Testing Script & Consent Form
Ledger-Software/Docs pull request #16
Opened 2017-03-17 22:55 UTC by LadyMopar

This PR contains both the script we'll use to do our usability testing and a consent form, since we wanna do things right.

Let me know if there's anything else that you think we should add to the script. I think I went through everything, but I might have skipped something important. If you've got time to kill, actually work through it yourself.

2017-03-18 18:51 UTC, shellajt requested changes
I would change the first sentence in the import step to: "Now we would like you to import a set of transactions into your newly created account."  You introduce the CSV/QFX files in the next sentence.

Other than that, looks good!

2017-03-18 19:26 UTC, shellajt approved these changes

2017-03-20 02:01 UTC, xxshadowfang approved these changes
Looks good to me.

2017-03-20 02:05 UTC, taylerhow approved these changes
Looks good!

2017-03-20 02:06 UTC, merged